/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package apis.handler;

import apis.model.Book;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-06-07T17:01:10.348764+09:00[Asia/Tokyo]")

@Validated
@Api(value = "books", description = "the books API")
public interface BooksApi {

    default BooksApiDelegate getDelegate() {
        return new BooksApiDelegate() {};
    }

    /**
     * DELETE /books/{bookId}
     *
     * @param bookId Book ID (required)
     * @return delete book (status code 204)
     */
    @ApiOperation(value = "", nickname = "booksBookIdDelete", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "delete book") })
    @RequestMapping(value = "/books/{bookId}",
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> booksBookIdDelete(@ApiParam(value = "Book ID",required=true) @PathVariable("bookId") String bookId) {
        return getDelegate().booksBookIdDelete(bookId);
    }


    /**
     * GET /books/{bookId}
     *
     * @param bookId Book ID (required)
     * @return get a book (status code 200)
     */
    @ApiOperation(value = "", nickname = "booksBookIdGet", notes = "", response = Book.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "get a book", response = Book.class) })
    @RequestMapping(value = "/books/{bookId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Book> booksBookIdGet(@ApiParam(value = "Book ID",required=true) @PathVariable("bookId") String bookId) {
        return getDelegate().booksBookIdGet(bookId);
    }


    /**
     * POST /books/{bookId}
     *
     * @param bookId Book ID (required)
     * @param book  (required)
     * @return create book (status code 201)
     */
    @ApiOperation(value = "", nickname = "booksBookIdPost", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "create book") })
    @RequestMapping(value = "/books/{bookId}",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> booksBookIdPost(@ApiParam(value = "Book ID",required=true) @PathVariable("bookId") String bookId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Book book) {
        return getDelegate().booksBookIdPost(bookId, book);
    }


    /**
     * PUT /books/{bookId}
     *
     * @param bookId Book ID (required)
     * @param book  (required)
     * @return update book (status code 204)
     */
    @ApiOperation(value = "", nickname = "booksBookIdPut", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "update book") })
    @RequestMapping(value = "/books/{bookId}",
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<Void> booksBookIdPut(@ApiParam(value = "Book ID",required=true) @PathVariable("bookId") String bookId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Book book) {
        return getDelegate().booksBookIdPut(bookId, book);
    }


    /**
     * GET /books
     *
     * @return get book list (status code 200)
     */
    @ApiOperation(value = "", nickname = "booksGet", notes = "", response = Book.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "get book list", response = Book.class, responseContainer = "List") })
    @RequestMapping(value = "/books",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<Book>> booksGet() {
        return getDelegate().booksGet();
    }

}
